
volumes:
  postgres_volume:

services:
  postgres:
    image: postgres:17.2-alpine3.20
    env_file:
      - "local.env"
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth:
    build:
      dockerfile: Dockerfile
      context: .
      no_cache: true
    env_file:
      - compose.env
    depends_on:
      postgres:
        condition: service_healthy
        required: true

    ports:
      - "8080:8000"

  migrator:
    build:
      context: .
      dockerfile: migration.dockerfile
    restart: on-failure
    environment:
      DB_HOST: postgres
